const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  INCREASE_ITEM_CART: 'INCREASE_ITEM_CART',
  DECREASE_ITEM_CART: 'DECREASE_ITEM_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartActionTypes;
